repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v1.7.1
#     hooks:
#     -   id: autopep8
# -   repo: https://github.com/hadialqattan/pycln
#     rev: v2.1.1
#     hooks:
#     -   id: pycln
#         args: [--config=pyproject.toml]

# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v1.2.3
#     hooks:
#     -   id: flake8
#         args:
#             - "--max-line-length=120"
#             - "--ignore=W605,E226,F841"
